"""initial schema

Revision ID: 650c509fb940
Revises: 
Create Date: 2026-06-24 08:00:53.938706
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '650c509fb940'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_table('llm_calls',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('prompt_template_code', sa.String(length=64), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=32), nullable=True),
    sa.Column('output_schema_code', sa.String(length=64), nullable=True),
    sa.Column('output_schema_version', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('request_checksum', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_purpose'), 'llm_calls', ['purpose'], unique=False)
    op.create_table('output_schemas',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('json_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_output_schema_code_version')
    )
    op.create_index(op.f('ix_output_schemas_code'), 'output_schemas', ['code'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('system_template', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('provider_hint', sa.String(length=64), nullable=True),
    sa.Column('model_hint', sa.String(length=64), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_prompt_code_version')
    )
    op.create_index(op.f('ix_prompt_templates_code'), 'prompt_templates', ['code'], unique=False)
    op.create_table('subjects',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('interface_language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('error_taxonomies',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_taxonomy_code_version')
    )
    op.create_index(op.f('ix_error_taxonomies_code'), 'error_taxonomies', ['code'], unique=False)
    op.create_table('exam_profiles',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'code', name='uq_exam_profile_code')
    )
    op.create_index(op.f('ix_exam_profiles_code'), 'exam_profiles', ['code'], unique=False)
    op.create_index(op.f('ix_exam_profiles_subject_id'), 'exam_profiles', ['subject_id'], unique=False)
    op.create_table('skills',
    sa.Column('exam_profile_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_profile_id'], ['exam_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_profile_id', 'code', name='uq_skill_code')
    )
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=False)
    op.create_index(op.f('ix_skills_exam_profile_id'), 'skills', ['exam_profile_id'], unique=False)
    op.create_table('task_families',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('answer_format', sa.String(length=32), nullable=False),
    sa.Column('default_evaluator_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'code', name='uq_task_family_code')
    )
    op.create_index(op.f('ix_task_families_code'), 'task_families', ['code'], unique=False)
    op.create_index(op.f('ix_task_families_skill_id'), 'task_families', ['skill_id'], unique=False)
    op.create_table('guidelines',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('exam_profile_id', sa.Uuid(), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('task_family_id', sa.Uuid(), nullable=True),
    sa.Column('frontmatter', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exam_profile_id'], ['exam_profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['task_family_id'], ['task_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_guideline_code_version')
    )
    op.create_index(op.f('ix_guidelines_code'), 'guidelines', ['code'], unique=False)
    op.create_table('rubrics',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('exam_profile_id', sa.Uuid(), nullable=True),
    sa.Column('task_family_id', sa.Uuid(), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_profile_id'], ['exam_profiles.id'], ),
    sa.ForeignKeyConstraint(['task_family_id'], ['task_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_rubric_code_version')
    )
    op.create_index(op.f('ix_rubrics_code'), 'rubrics', ['code'], unique=False)
    op.create_table('training_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('exam_profile_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('task_family_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_earned', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exam_profile_id'], ['exam_profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['task_family_id'], ['task_families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_status'), 'training_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('dependency_rules',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_rules_rubric_id'), 'dependency_rules', ['rubric_id'], unique=False)
    op.create_table('evaluation_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('task_family_id', sa.Uuid(), nullable=True),
    sa.Column('evaluator_code', sa.String(length=64), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_template_id', sa.Uuid(), nullable=True),
    sa.Column('output_schema_id', sa.Uuid(), nullable=True),
    sa.Column('error_taxonomy_id', sa.Uuid(), nullable=True),
    sa.Column('provider_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['error_taxonomy_id'], ['error_taxonomies.id'], ),
    sa.ForeignKeyConstraint(['output_schema_id'], ['output_schemas.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.ForeignKeyConstraint(['task_family_id'], ['task_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_eval_profile_code_version')
    )
    op.create_index(op.f('ix_evaluation_profiles_code'), 'evaluation_profiles', ['code'], unique=False)
    op.create_table('penalty_rules',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalty_rules_rubric_id'), 'penalty_rules', ['rubric_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'code', name='uq_criterion_code')
    )
    op.create_index(op.f('ix_rubric_criteria_rubric_id'), 'rubric_criteria', ['rubric_id'], unique=False)
    op.create_table('performance_bands',
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=False),
    sa.Column('machine_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_bands_criterion_id'), 'performance_bands', ['criterion_id'], unique=False)
    op.create_table('task_blueprints',
    sa.Column('task_family_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('recommended_minutes', sa.Integer(), nullable=True),
    sa.Column('target_word_count_min', sa.Integer(), nullable=True),
    sa.Column('target_word_count_max', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('generator_profile_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_profile_id', sa.Uuid(), nullable=True),
    sa.Column('rubric_id', sa.Uuid(), nullable=True),
    sa.Column('guideline_id', sa.Uuid(), nullable=True),
    sa.Column('content_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generation_constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_profile_id'], ['evaluation_profiles.id'], ),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.ForeignKeyConstraint(['task_family_id'], ['task_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_blueprint_code_version')
    )
    op.create_index(op.f('ix_task_blueprints_code'), 'task_blueprints', ['code'], unique=False)
    op.create_index(op.f('ix_task_blueprints_task_family_id'), 'task_blueprints', ['task_family_id'], unique=False)
    op.create_table('task_instances',
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('guideline_id', sa.Uuid(), nullable=True),
    sa.Column('guideline_version', sa.String(length=32), nullable=True),
    sa.Column('generator_prompt_id', sa.Uuid(), nullable=True),
    sa.Column('generator_prompt_version', sa.String(length=32), nullable=True),
    sa.Column('generator_model', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('solution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('hints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recommended_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['task_blueprints.id'], ),
    sa.ForeignKeyConstraint(['generator_prompt_id'], ['prompt_templates.id'], ),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_instances_blueprint_id'), 'task_instances', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_task_instances_checksum'), 'task_instances', ['checksum'], unique=False)
    op.create_index(op.f('ix_task_instances_status'), 'task_instances', ['status'], unique=False)
    op.create_table('attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('raw_answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evaluator_code', sa.String(length=64), nullable=True),
    sa.Column('evaluation_profile_id', sa.Uuid(), nullable=True),
    sa.Column('score_raw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('penalty_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_final', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_profile_id'], ['evaluation_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_idempotency_key'), 'attempts', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_attempts_session_id'), 'attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_attempts_task_id'), 'attempts', ['task_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('session_tasks',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_tasks_session_id'), 'session_tasks', ['session_id'], unique=False)
    op.create_table('task_media',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('public_or_signed_url', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_media_task_id'), 'task_media', ['task_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('penalty_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_provider_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('provider_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_attempt_id'), 'evaluation_results', ['attempt_id'], unique=False)
    op.create_table('content_point_assessments',
    sa.Column('evaluation_result_id', sa.Uuid(), nullable=False),
    sa.Column('content_point_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_point_assessments_evaluation_result_id'), 'content_point_assessments', ['evaluation_result_id'], unique=False)
    op.create_table('criterion_scores',
    sa.Column('evaluation_result_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_code', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('selected_band', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criterion_scores_evaluation_result_id'), 'criterion_scores', ['evaluation_result_id'], unique=False)
    op.create_table('error_events',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_result_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('source_fragment', sa.Text(), nullable=True),
    sa.Column('corrected_fragment', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('criterion_code', sa.String(length=64), nullable=True),
    sa.Column('content_point_id', sa.String(length=64), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_events_attempt_id'), 'error_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_error_events_evaluation_result_id'), 'error_events', ['evaluation_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_events_evaluation_result_id'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_attempt_id'), table_name='error_events')
    op.drop_table('error_events')
    op.drop_index(op.f('ix_criterion_scores_evaluation_result_id'), table_name='criterion_scores')
    op.drop_table('criterion_scores')
    op.drop_index(op.f('ix_content_point_assessments_evaluation_result_id'), table_name='content_point_assessments')
    op.drop_table('content_point_assessments')
    op.drop_index(op.f('ix_evaluation_results_attempt_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_task_media_task_id'), table_name='task_media')
    op.drop_table('task_media')
    op.drop_index(op.f('ix_session_tasks_session_id'), table_name='session_tasks')
    op.drop_table('session_tasks')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_task_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_session_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_idempotency_key'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_task_instances_status'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_checksum'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_blueprint_id'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_task_blueprints_task_family_id'), table_name='task_blueprints')
    op.drop_index(op.f('ix_task_blueprints_code'), table_name='task_blueprints')
    op.drop_table('task_blueprints')
    op.drop_index(op.f('ix_performance_bands_criterion_id'), table_name='performance_bands')
    op.drop_table('performance_bands')
    op.drop_index(op.f('ix_rubric_criteria_rubric_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_penalty_rules_rubric_id'), table_name='penalty_rules')
    op.drop_table('penalty_rules')
    op.drop_index(op.f('ix_evaluation_profiles_code'), table_name='evaluation_profiles')
    op.drop_table('evaluation_profiles')
    op.drop_index(op.f('ix_dependency_rules_rubric_id'), table_name='dependency_rules')
    op.drop_table('dependency_rules')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_status'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_rubrics_code'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_guidelines_code'), table_name='guidelines')
    op.drop_table('guidelines')
    op.drop_index(op.f('ix_task_families_skill_id'), table_name='task_families')
    op.drop_index(op.f('ix_task_families_code'), table_name='task_families')
    op.drop_table('task_families')
    op.drop_index(op.f('ix_skills_exam_profile_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_exam_profiles_subject_id'), table_name='exam_profiles')
    op.drop_index(op.f('ix_exam_profiles_code'), table_name='exam_profiles')
    op.drop_table('exam_profiles')
    op.drop_index(op.f('ix_error_taxonomies_code'), table_name='error_taxonomies')
    op.drop_table('error_taxonomies')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_prompt_templates_code'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_output_schemas_code'), table_name='output_schemas')
    op.drop_table('output_schemas')
    op.drop_index(op.f('ix_llm_calls_purpose'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
