"""dictionary, user words and flashcard reviews

Revision ID: ef7aaad0c99d
Revises: 02b7480fa765
Create Date: 2026-06-24 12:51:21.456114
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ef7aaad0c99d'
down_revision: str | None = '02b7480fa765'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('source_language', sa.String(length=8), nullable=False),
    sa.Column('target_language', sa.String(length=8), nullable=False),
    sa.Column('original_query', sa.String(length=255), nullable=False),
    sa.Column('normalized_word', sa.String(length=255), nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=True),
    sa.Column('part_of_speech', sa.String(length=64), nullable=True),
    sa.Column('translations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('definitions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('phonetics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('audio_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('forms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('synonyms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('provider_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_provider_responses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_language', 'target_language', 'normalized_word', name='uq_dictionary_cache_key')
    )
    op.create_index(op.f('ix_dictionary_entries_normalized_word'), 'dictionary_entries', ['normalized_word'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_source_language'), 'dictionary_entries', ['source_language'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_target_language'), 'dictionary_entries', ['target_language'], unique=False)
    op.create_table('user_words',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dictionary_entry_id', sa.Uuid(), nullable=True),
    sa.Column('knowledge_level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_entry_id'], ['dictionary_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_words_next_review_at'), 'user_words', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_user_words_user_id'), 'user_words', ['user_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('user_word_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_word_id'], ['user_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_reviews_user_word_id'), 'flashcard_reviews', ['user_word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcard_reviews_user_word_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_user_words_user_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_next_review_at'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_dictionary_entries_target_language'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_source_language'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_normalized_word'), table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    # ### end Alembic commands ###
